apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sampleappdeploy
  namespace: unicorn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: mazuma5/simple-maven-webapp:33
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sampleappsvc
  namespace: unicorn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sampleapp
